repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^tests/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    id: flake8
    args: [
            '--per-file-ignores=__init__.py:F401',
            '--max-line-length=88',
            '--ignore=E1,W1,E2,W2,E4,W4,E5,W5' # Handled by black
        ]

# Sorts imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]


