[tool.taskipy.tasks]
coverage = "coverage html && open htmlcov/index.html"
docs = "mkdocs serve"
#test = "pytest -s -x --cov=pylme -vv"


[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"

[tool.ruff]
extend-select = [
"E/W"
]
